
version: 0.1
phases:
  install:
    commands:
      - npm install --prefix ./timeResource time
      - npm install --prefix ./getClassDetails request
      - npm install --prefix ./getClassDetails aws4
      - npm install --prefix ./getUserDetails request
      - npm install --prefix ./getUserDetails aws4
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket sample-gradebook-build 
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
